const express = require('express');
const route = express.Router();
const passport = require('passport');
const ClientController = require('../app/controllers/ClientController');
const middleware = require('../config/middleware');
route.get('/', middleware.checkrole,ClientController.client);
route.get('/logout',ClientController.logout);
route.get('/about', middleware.checkrole,ClientController.about);
route.get('/contact',middleware.checkrole,ClientController.contact);
route.get('/post/:id',middleware.checkrole,ClientController.post);
route.post('/login', passport.authenticate('local', { successRedirect: '/', failureRedirect: '/logincheck', failureFlash : true, badRequestMessage: 'Input(s) empty!' }));
route.get('/login',ClientController.login);
route.get('/logincheck',ClientController.logincheck);
route.get('/register',ClientController.register);
route.post('/registercheck',ClientController.registercheck);
route.post('/comment',ClientController.comment);
route.post('/comment/check',ClientController.commentCheck);
route.post('/comment/delete',ClientController.commentDeleteClient);
route.post('/comment/update',ClientController.commentUpdateClient);
module.exports = route;